version: '3'

services:
  api:
    build: .
    ports:
      - "25002:5000"
    volumes:
      - ./checkpoint:/app/checkpoint
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    restart: unless-stopped 