version: '3'

services:
  api:
    build: .
    ports:
      - "25004:5000"
    volumes:
      - ./eval_config:/app/eval_config
      - ./eval_result:/app/eval_result
      - ./graph_dataset:/app/graph_dataset
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    restart: unless-stopped 